{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: petclinic-db-secret
  labels:
    {{- include "petclinic.commonLabels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: password
    - secretKey: MYSQL_USER
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: username
    - secretKey: MYSQL_HOST
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: endpoint
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: dbname
{{- end }}
