{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  labels:
    {{- include "petclinic-secrets.commonLabels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: {{ .Values.externalSecret.creationPolicy }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecret.remoteSecretName }}
        property: {{ .remoteProperty }}
    {{- end }}
{{- end }}
