{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "petclinic-service.fullname" . }}
  labels:
    {{- include "petclinic-service.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "petclinic-service.name" . }}
spec:
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "petclinic-service.selectorLabels" . | nindent 6 }}
{{- end }}
