apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic-service.fullname" . }}
  labels:
    {{- include "petclinic-service.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "petclinic-service.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "petclinic-service.selectorLabels" . | nindent 4 }}
