apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - petclinic-secrets-prod.yaml
  - config-server-prod.yaml
  - discovery-server-prod.yaml
  - api-gateway-prod.yaml
  - customers-service-prod.yaml
  - visits-service-prod.yaml
  - vets-service-prod.yaml
  - genai-service-prod.yaml
  - admin-server-prod.yaml
