image:
  registry: 536697234487.dkr.ecr.us-east-1.amazonaws.com
  repositoryPrefix: petclinic-dev
  tag: 440a8a7ba41a14445e8105394c998fbad8049f82

exposure:
  apiGatewayServiceType: ClusterIP

ingress:
  enabled: false
  className: alb
  host: ""
  certificateArn: ""
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreName: aws-secrets-manager
  targetSecretName: mysql-secret
  remoteSecretName: petclinic/database-credentials

monitoring:
  podMonitor:
    enabled: true

services:
  config-server:
    replicaCount: 1
    port: 8888
    profile: default
    mysql: false

  discovery-server:
    replicaCount: 1
    port: 8761
    profile: docker
    mysql: false

  api-gateway:
    replicaCount: 1
    port: 8080
    profile: docker
    mysql: false

  customers-service:
    replicaCount: 1
    port: 8081
    profile: docker,mysql
    mysql: true

  vets-service:
    replicaCount: 1
    port: 8083
    profile: docker,mysql
    mysql: true

  visits-service:
    replicaCount: 1
    port: 8082
    profile: docker,mysql
    mysql: true

  admin-server:
    replicaCount: 1
    port: 9090
    profile: docker
    mysql: false

  genai-service:
    replicaCount: 1
    port: 8084
    profile: docker
    mysql: false
    waitForDiscovery: true
    openaiSecret: true
