apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: petclinic-db-secret
  namespace: petclinic
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: petclinic/db-credentials
      property: password
  - secretKey: MYSQL_USER
    remoteRef:
      key: petclinic/db-credentials
      property: username
  - secretKey: MYSQL_HOST
    remoteRef:
      key: petclinic/db-credentials
      property: endpoint
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: petclinic/db-credentials
      property: dbname
