image:
  tag: "34445e5"

service:
  name: admin-server
  port: 9090
  targetPort: http

container:
  port: 9090

spring:
  profiles: docker

dependencies:
  configServer:
    enabled: true
  discoveryServer:
    enabled: false
