image:
  tag: "8a4e8e4"

service:
  name: api-gateway
  port: 80
  targetPort: http

container:
  port: 8080

spring:
  profiles: docker

dependencies:
  configServer:
    enabled: true
  discoveryServer:
    enabled: true

probes:
  startup:
    enabled: true
    path: /actuator/health
    periodSeconds: 10
    failureThreshold: 30
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 15
    failureThreshold: 3
