image:
  tag: 19039bd

service:
  name: api-gateway
  port: 80
  targetPort: http
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip

container:
  port: 8080

spring:
  profiles: docker

dependencies:
  configServer:
    enabled: true
  discoveryServer:
    enabled: true

probes:
  startup:
    enabled: true
    path: /actuator/health
    periodSeconds: 10
    failureThreshold: 30
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 15
    failureThreshold: 3
