image:
  tag: "8a4e8e4"

service:
  name: config-server
  port: 8888
  targetPort: http

container:
  port: 8888

spring:
  profiles: default

dependencies:
  configServer:
    enabled: false
  discoveryServer:
    enabled: false
