image:
  tag: "6d2c695"

service:
  name: customers-service
  port: 8081
  targetPort: http

container:
  port: 8081

spring:
  profiles: docker,mysql

dependencies:
  configServer:
    enabled: true
  discoveryServer:
    enabled: true

mysql:
  enabled: true
