image:
  tag: "4c0d043"

service:
  name: discovery-server
  port: 8761
  targetPort: http

container:
  port: 8761

spring:
  profiles: docker

dependencies:
  configServer:
    enabled: true
  discoveryServer:
    enabled: false
