image:
  tag: "a99d4d6"

service:
  name: vets-service
  port: 8083
  targetPort: http

container:
  port: 8083

spring:
  profiles: docker,mysql

dependencies:
  configServer:
    enabled: true
  discoveryServer:
    enabled: true

mysql:
  enabled: true
